jest, migration
pnpm/pnpm pull request #2924
Opened 2020-10-12 20:34 UTC by juanpicado

- /pnpm/packages/git-fetcher
- /pnpm/packages/global-bin-dir

2020-10-12 20:49 UTC, zkochan requested changes

2020-10-12 20:49 UTC, zkochan commented on packages/git-fetcher/package.json
> +    "_test": "jest",
seems not right

2020-10-12 20:49 UTC, zkochan commented on packages/git-fetcher/test/index.ts
> +  const name = (await manifest.promise).name;
we don't use semicolons

2020-10-12 20:49 UTC, zkochan commented on packages/global-bin-dir/package.json
>      "_test": "cd ../.. && c8 --reporter lcov --reports-dir packages/global-bin-dir/coverage ts-node packages/global-bin-dir/test --type-check"
I think you had to update this script and keep test as it was

2020-10-12 20:51 UTC, juanpicado commented on packages/git-fetcher/test/index.ts
> +  const name = (await manifest.promise).name;
Odd .. how this passed eslint ...

2020-10-14 05:48 UTC, juanpicado commented
This is all for this PR, I'll continue later with other packages are a bit more complex.

2020-10-14 10:09 UTC, merged