feat: change default publish branch to main or default branch in git config
pnpm/pnpm pull request #3064
Opened 2021-01-11 22:37 UTC by yaodingyd

close #2995

2021-01-11 22:47 UTC, zkochan requested changes

2021-01-11 22:47 UTC, zkochan commented on packages/plugin-commands-publishing/src/publish.ts
> +    const branch = opts.publishBranch ?? (await getDefaultBranch() || 'main')
let's make it an array and allow both main and master. In that case, it won't be a breaking change

2021-01-11 23:47 UTC, zkochan requested changes

2021-01-11 23:47 UTC, zkochan commented on packages/plugin-commands-publishing/src/publish.ts
> +        message: `You're on branch "${currentBranch}" but your "publish-branch" is set to "${branches.join('/')}". \
a branch name may contain `/`, so to avoid confusion, let's probably use `|` to join the branch names. And in the error as well

2021-01-11 23:55 UTC, zkochan commented on .changeset/green-suns-argue.md
> +Change default publish branch to main or defaultBranch in git config
this file should be removed.

2021-01-12 00:53 UTC, zkochan commented on packages/plugin-commands-publishing/src/publish.ts
> +        throw new PnpmError('GIT_NOT_CORRECT_BRANCH', `Branch is not on '${branches.join('/')}'.`, {
```suggestion
        throw new PnpmError('GIT_NOT_CORRECT_BRANCH', `Branch is not on '${branches.join('|')}'.`, {
```

2021-01-12 00:53 UTC, zkochan commented on packages/plugin-commands-publishing/test/gitChecks.ts
> +    new PnpmError('GIT_NOT_CORRECT_BRANCH', "Branch is not on 'master/main'.")
```suggestion
    new PnpmError('GIT_NOT_CORRECT_BRANCH', "Branch is not on 'master|main'.")
```

2021-01-12 10:54 UTC, zkochan approved these changes

2021-01-13 00:40 UTC, zkochan commented
I am unsure if using `init.defaultBranch` is right. It only gets what the global configuration is for newly created repositories, right? But the active repository's main branch might be different.

2021-01-13 01:05 UTC, yaodingyd commented
> I am unsure if using `init.defaultBranch` is right. It only gets what the global configuration is for newly created repositories, right? But the active repository's main branch might be different.

Good point. Let me rework on this

2021-01-13 01:26 UTC, zkochan commented
all we can do is just allow "main" and "master". I don't see a good way to find the default branch name automatically.

2021-01-13 01:38 UTC, yaodingyd commented
how about
```
funtion optimisticallyGetDefaultBranch() {
	// git remote show origin | grep "HEAD branch" | cut -d ":" -f 2
}
```

or just `main|master`. I'm fine with that too

2021-01-13 01:51 UTC, zkochan commented
Not sure about that. Making requests to the remote repository has many drawbacks. Like from some users it will aks the password.

Also, your suggested solution will only work when the Git CLI prints info in English.

2021-01-13 01:54 UTC, zkochan commented
This PR is being merged to master. We don't use master. We now use main as the default branch.

2021-01-13 09:56 UTC, merged