fix(npm-resolver): unhandled rejection in fetch
pnpm/pnpm pull request #3413
Opened 2021-05-02 01:10 UTC by amitgilad3

When fetch command fails for any reason catch it and return FetchError to avoid Unhandled rejection

ref #3261

2021-05-02 09:00 UTC, zkochan requested changes

2021-05-02 09:00 UTC, zkochan commented on packages/npm-resolver/src/fetch.ts
> +        console.log(error)
this is not needed

2021-05-02 09:00 UTC, zkochan commented on packages/error/src/index.ts
> +export interface FetchErrorResponse { status: number | string, statusText: string }
This error object was created for errors that have an http status respond, so I think it is better no to change it.

2021-05-02 09:00 UTC, zkochan commented on packages/npm-resolver/src/fetch.ts
> +        }, { status: error.code, statusText: error.message }))
Probably best to use the generic error object

```ts
reject(new PnpmError('META_FETCH_FAIL', `GET ${uri}: ${err.message}`, { attempts: attempt }))
```

2021-05-03 19:49 UTC, amitgilad3 commented on packages/npm-resolver/src/fetch.ts
> +        console.log(error)
my mistake 👍

2021-05-03 19:49 UTC, zkochan commented on .changeset/little-dragons-wave.md
> +"@pnpm/error": patch
This line should be removed.

2021-05-03 19:49 UTC, amitgilad3 commented on packages/error/src/index.ts
> +export interface FetchErrorResponse { status: number | string, statusText: string }
thanks for the explanation , makes perfect sense

2021-05-03 19:55 UTC, zkochan approved these changes

2021-05-03 20:19 UTC, amitgilad3 commented
sorry for the inconvenience , this is my first pr , will pay more attention to errors in the future.
i fixed the failing tests but locally on branch main not all test pass (without my fixes),  is that the current state ? @zkochan

2021-05-03 20:30 UTC, zkochan commented
Tests seem to pass on main. What is your OS?

2021-05-03 21:28 UTC, merged

2021-05-03 21:42 UTC, amitgilad3 commented
macos