fix: pnpm doesn't respect save-prefix
pnpm/pnpm pull request #3420
Opened 2021-05-05 23:33 UTC by amitgilad3

this fix is intended to align pnpm behavior to npm when it comes to the save-prefix flag.

fixes #3414

2021-05-05 23:43 UTC, zkochan approved these changes

2021-05-05 23:56 UTC, zkochan commented
How did you align it with npm's behavior? Seems like you did some breaking changes.

2021-05-06 08:22 UTC, amitgilad3 commented
> How did you align it with npm's behavior? Seems like you did some breaking changes.

The intention of the task was to align save-prefix behavior to be the same as npm.

1. When running pnpm add is-positive@1.0.0(specific version specified) , pnpm should add default prefix or use what was specified in config. the current state will save the package like this 

current result: 
```
dependencies: {
"is-positive": "1.0.0"
}
```

expected result: 
```
dependencies: {
"is-positive": "^1.0.0"
}
```
2. When setting save-prefix with empty string pnpm should not set a prefix.

I did some investigating and it seems that most of the tests  broke because of the first fix i did (pnpm add is-positive@1.0.0(specific package version specified) since until now when you run this command pnpm does not add a prefix .

i am planning on fixing all the test that broke, do you think that making this change makes sense @zkochan  ?

2021-05-06 08:40 UTC, zkochan commented
No, please don't change this behavior. @vjpr asked for this behavior and I think it makes sense. We do not always clone npm's behavior.

`pnpm add is-positive@1.0.0` adds `1.0.0` to `package.json`. This is the expected behavior of pnpm. `pnpm add is-positive` adds the version with the specified prefix but when the range is explicitly specified, then the specified range is added with no modifications.

2021-05-06 08:43 UTC, zkochan requested changes
Please do not change the way dependencies are added, when a range is specified explicitly.

2021-05-06 09:02 UTC, amitgilad3 commented
> No, please don't change this behavior. @vjpr asked for this behavior and I think it makes sense. We do not always clone npm's behavior.

I agree that we shouldn't clone npm's behavior all the time , this way makes more sense. 
thanks for the explanation , i will fix this :)

2021-05-06 11:12 UTC, zkochan approved these changes

2021-05-06 11:50 UTC, merged