fix(default-reporter): use loglevel to filter deprecation warnings (#4343)
pnpm/pnpm pull request #4507
Opened 2022-03-30 14:10 UTC by milahu

fix #4343 

... at least for `WARN deprecated`

successfully tested with `node /path/to/pnpm/packages/pnpm/spnpm.js install --loglevel error --lockfile-only`

2022-03-30 14:27 UTC, zkochan requested changes
Add changesets and a test.

2022-03-30 14:27 UTC, zkochan commented on packages/default-reporter/src/reporterForClient/reportDeprecations.ts
> +    filter((log) => log.depth === 0),
We need to print deprecation messages from all levels.

2022-03-30 14:27 UTC, zkochan commented on packages/default-reporter/src/reporterForClient/reportDeprecations.ts
> +    filter(() => opts.logLevel != 'error'),
In this case, the stream should not be even read. Just return an empty stream instead, if loglevel is set to error.

2022-03-30 20:22 UTC, milahu commented
changesets?

test seems challenging ...
i had a look at `packages/default-reporter/test/index.ts`
but i dont see a way to do `log$.deprecation.next(...)`
integration test should be easier. ideas?

2022-04-01 08:24 UTC, milahu commented
thanks for your fix : )

while we're at it
i suggest we hide the progress reporting on loglevel=error and loglevel=warn

2022-04-01 14:38 UTC, zkochan commented
I'll have to look into it. Covering it with an e2e test is too expensive.

2022-04-17 01:00 UTC, zkochan approved these changes

2022-04-17 01:24 UTC, merged