feat: enhance peer dependency rules
pnpm/pnpm pull request #4876
Opened 2022-06-10 17:25 UTC by TravisJRyan

**Issue**
Ref #4835 

**Summary**
This PR adds two enhancements to `peerDependencyRules`:
- Expands `ignoreMissing` support with pattern matching
- Adds a comparable `ignoreVersion` field to peer dependency rules which will allow any version of a given peer dependency (also pattern-matched) to exist. Pnpm already supports this with exhaustively listed dependencies and a "*" for allowed version, so this field adds comparable functionality to the `ignoreMissing` above with a pattern-matched list.

**Justification**
This should allow pnpm greater control of peer dependency warnings without encouraging silencing warnings with something like a "silence all warnings" flag, as discussed in the issue. Users will have greater flexibility on which peer warnings (dependency missing or version-related) that they ignore and reduce noise.

Open to any feedback. Thanks for having a look.

2022-06-11 01:08 UTC, zkochan requested changes
Add changesets

2022-06-11 01:08 UTC, zkochan commented on packages/core/src/install/createPeerDependencyPatcher.ts
> +        matcher(ignoreMissingPatterns)(peerName) &&
Don't recreate the matcher on each iteration. Init it once outside the loop.

2022-06-11 01:08 UTC, zkochan commented on packages/core/test/install/createPeerDependencyPatcher.test.ts
> +    ignoreVersion: ['foo', 'bar'],
a better name for this field might be `allowAny`

2022-06-11 01:08 UTC, zkochan commented on packages/core/src/install/createPeerDependencyPatcher.ts
> +      if (peerVersion !== '*' && matcher(ignoreVersionPatterns)(peerName)) {
don't reinitialize the matcher on every iteration.

2022-06-11 01:08 UTC, zkochan commented on packages/core/src/install/createPeerDependencyPatcher.ts
>          peerVersion !== '*'
both if statements check for `peerVersion !== '*'`. It can be moved to one place.

2022-06-11 01:08 UTC, zkochan commented on packages/core/src/install/createPeerDependencyPatcher.ts
> +  const ignoreVersionPatterns = [...new Set(peerDependencyRules.ignoreVersion ?? [])]
I think `ignoreVersion` is just syntax sugar for allowedVersions. So, you can extend allowedVersions with the packages from `ignoreVersion` and make no changes in this function related to ignoreVersion

2022-06-13 09:09 UTC, zkochan approved these changes

2022-06-13 11:19 UTC, TravisJRyan commented
@zkochan Thanks for your follow-up on this - let me know if you need anything else from me to move ahead with this.

2022-06-13 19:39 UTC, merged