Fix pnpm audit bad API response on private registry
pnpm/pnpm pull request #5246
Opened 2022-08-22 23:26 UTC by timtong1982

2022-08-22 23:27 UTC, timtong1982 commented
#5200

2022-08-22 23:29 UTC, zkochan commented
In that issue you are saying that a 404 error should be treated differently. I don't see that here.

2022-08-22 23:30 UTC, timtong1982 commented
> In that issue you are saying that a 404 error should be treated differently. I don't see that here.

then we need expose the http status code all the way from packages/audit/src/index.ts

2022-08-22 23:31 UTC, timtong1982 commented
> > In that issue you are saying that a 404 error should be treated differently. I don't see that here.
> 
> then we need expose the http status code all the way from packages/audit/src/index.ts

or create a new type of error

I will work on that

2022-08-23 07:49 UTC, zkochan commented on packages/plugin-commands-audit/src/audit.ts
> +    }
```suggestion
    throw err
```

You should just throw the error. pnpm will exit with 1 and print the error correctly

2022-08-23 07:50 UTC, zkochan requested changes
Run `pnpm changeset` in the root of the repository and describe your changes. The resulting files should be committed as they will be used during release.

2022-08-23 15:33 UTC, timtong1982 commented
> Run `pnpm changeset` in the root of the repository and describe your changes. The resulting files should be committed as they will be used during release.

Thanks, updated.

2022-08-23 22:26 UTC, zkochan approved these changes

2022-08-23 22:44 UTC, merged