fix: fix the check for Node in the system
pnpm/pnpm pull request #6686
Opened 2023-06-16 13:17 UTC by illright

Closes #6685

2023-06-17 10:39 UTC, zkochan commented on config/package-is-installable/src/getSystemNodeVersion.ts
>    }
You are breaking node.js check on systems that have node. This is the way we need to check the version of node.js in the packages version of pnpm (where we bundle pnpm with node.js)

The right solution is probably to do something like
```suggestion
  if (process['pkg'] != null) {
    try {
      return execa.sync('node', ['--version']).stdout.toString()
    } catch (err) {
      // There is no Node.js on the system
      return null
    }
  }
```

2023-06-17 10:39 UTC, zkochan commented on config/package-is-installable/test/getSystemNodeVersion.test.ts
These tests should not be changed

2023-06-17 10:40 UTC, zkochan requested changes
See my comments

2023-06-18 05:42 UTC, illright commented
@zkochan please help me understand where my reasoning is wrong: 

The `process['pkg']` is set only in pnpm installations that bundle Node in, and those installations also have `process.version`, so when `process['pkg']` is not null, we shouldn't check `node --version` because it might not be there.

If `process['pkg']` is null, then pnpm isn't bundled with Node, and therefore must be running on Node that's installed externally in the system. That means it's safe to spawn `node --version`

2023-06-18 09:01 UTC, zkochan commented
We should not check the node.js version with which pnpm is bundled because that node.js is only used for running the pnpm code, not for running scripts of "outside" projects.

2023-06-19 08:22 UTC, illright commented
Fair enough, but then I don't understand what causes the original issue. I'll close this PR for now, let's move over to that issue for further discussion

2023-06-19 08:22 UTC, closed without merging