fix: add support for npm lockfile v3 in `import`
pnpm/pnpm pull request #6931
Opened 2023-08-10 09:41 UTC by nachoaldamav

closes #6233

2023-08-10 11:16 UTC, zkochan requested changes
Cover this with a test

2023-08-17 09:41 UTC, zkochan commented on pkg-manager/plugin-commands-installation/src/import/index.ts
> +        // @ts-expect-error
This should be removed

2023-08-17 12:54 UTC, zkochan approved these changes

2023-08-17 13:51 UTC, merged

2024-12-30 10:20 UTC, landed1 commented
Hi Noob question. I started to use pnpm and now dont have a lock file. This is giving me an error when I try to build on github pages. So I found that the defualt build script provided by Github is not designed for pnpm. So I used AI to get the following:

`# Workflow for building and deploying a Next.js site to GitHub Pages using pnpm
name: Deploy Next.js site to Pages

on:
  push:
    branches: ["main"] # Trigger on push to the main branch
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Specify your Node.js version
          cache: pnpm # Cache dependencies for pnpm

      - name: Install pnpm
        run: npm install -g pnpm # Install pnpm globally

      - name: Restore dependencies
        run: pnpm install # Use pnpm to install dependencies

      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: next

      - name: Build with Next.js
        run: pnpm next build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out # Ensure this matches your Next.js `output` configuration

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
`
This installs the pnpm program so I don't know why it still fails. 

Error : Unable to locate executable file: pnpm. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.