feat: add option to filter licenses list
pnpm/pnpm pull request #7204
Opened 2023-10-15 08:33 UTC by aiji42

closes https://github.com/pnpm/pnpm/issues/5806

## Overview

Added option to output only licenses for specific workspaces when running `pnpm licenses list`.

## Details

I added the `--importer` option. This is an option to filter the license results by the key of importers in the lock file.

```
❯ pnpm licenses list -h  
Version 8.9.0
Usage: pnpm licenses ls
       pnpm licenses list
       pnpm licenses list --long

Check the licenses of the installed packages.

Options:
  -D, --dev                Check only "devDependencies"
      --importer <dir>     Restrict output to importer names matching the given. The importer names are listed in the lock file.
      ^^^^^^^^^^^^^^^^^
      --json               Show information in JSON format
      --long               Show more details (such as a link to the repo) are not displayed. To display the details, pass this option.
      --no-optional        Don't check "optionalDependencies"
  -P, --prod               Check only "dependencies" and "optionalDependencies"

Visit https://pnpm.io/8.x/cli/licenses for documentation about this command.
```

This is the result of running it in the pnpm repository.

```
> pnpm licenses list -P
┌────────────────────────────────────────┬───────────────────────────┐
│ Package                                │ License                   │
├────────────────────────────────────────┼───────────────────────────┤
│ json-schema                            │ (AFL-2.1 OR BSD-3-Clause) │
├────────────────────────────────────────┼───────────────────────────┤
│ JSONStream                             │ (MIT OR Apache-2.0)       │
├────────────────────────────────────────┼───────────────────────────┤
│ type-fest                              │ (MIT OR CC0-1.0)          │
├────────────────────────────────────────┼───────────────────────────┤
│ tslib                                  │ 0BSD                      │
so match more ...
```

Use --import to filter output to the specified directory.

```
❯ pnpm licenses list --importer config/matcher -P           
┌──────────────────────┬─────────┐
│ Package              │ License │
├──────────────────────┼─────────┤
│ escape-string-regexp │ MIT     │
└──────────────────────┴─────────┘
```

2023-10-15 09:37 UTC, zkochan requested changes
We already have a `--filter` flag and `selectedProjectsGraph` is passed down to all plugins. The already present filtering mechanism should be used.

2023-10-15 12:43 UTC, aiji42 commented
@zkochan I fixed to use `--filter` 🙆‍♂️

2023-10-16 23:06 UTC, zkochan requested changes

2023-10-16 23:06 UTC, zkochan commented on reviewing/license-scanner/src/licenses.ts
> +  importerIds?: string[]
let's call it
```suggestion
  includedImporterIds?: string[]
```

2023-10-16 23:06 UTC, zkochan commented on reviewing/plugin-commands-licenses/test/fixtures/workspace-licenses/bar/package.json
> +  "license": "ISC",
remove these unnecessary fields

2023-10-16 23:06 UTC, zkochan commented on reviewing/plugin-commands-licenses/test/index.ts
> +test('pnpm licenses: filter outputs', async () => {
Why was an existing test removed?

2023-10-17 00:35 UTC, aiji42 commented on reviewing/plugin-commands-licenses/test/index.ts
> +test('pnpm licenses: filter outputs', async () => {
It was a mistake. I've corrected it.

2023-10-17 00:38 UTC, aiji42 commented
@zkochan Made the changes. Thank you for the feedback! Please review again.

2023-10-17 09:30 UTC, zkochan approved these changes

2023-10-17 10:12 UTC, merged