feat: add support to install different architectures
pnpm/pnpm pull request #7214
Opened 2023-10-17 16:55 UTC by nachoaldamav

This feature allows pnpm to force the install of dependencies for specific systems.

For example, with this `package.json`:
```json
{
  "pnpm": {
    "supportedArchitectures": {
      "os": ["darwin", "win32"],
      "cpu": ["x64", "arm64"]
    }
  }
}
```

pnpm will install the following dependencies for esbuild:
```bash
  - @esbuild+darwin-arm64@0.18.20
  - @esbuild+darwin-x64@0.18.20
  - @esbuild+win32-arm64@0.18.20
  - @esbuild+win32-x64@0.18.20
```

2023-10-18 14:47 UTC, zkochan requested changes

2023-10-18 14:47 UTC, zkochan commented on cli/cli-utils/src/readProjectManifest.ts
> +  }
avoid change to formatting unrelated to the changes
```suggestion
  } = {}
```

2023-10-18 14:47 UTC, zkochan commented on cli/cli-utils/src/readProjectManifest.ts
> +
avoid change to formatting unrelated to the changes

2023-10-18 14:47 UTC, zkochan commented on config/package-is-installable/src/checkPlatform.ts
> +function dedupeArchs (current: string, supported: string[]) {
This name of the function isn't good as it is used not only for arch. Maybe
```suggestion
function dedupeCurrent (current: string, supported: string[]) {
```

2023-10-18 14:47 UTC, zkochan commented on config/package-is-installable/src/checkPlatform.ts
> +  return result
I guess a more effective way would be to do something like this
```suggestion
  return supportedList.map((supported) => supported === 'current' ? current : supported)
```

2023-10-18 14:47 UTC, zkochan commented on exec/plugin-commands-script-runners/test/index.ts
> +
revert the new lines in the file

2023-10-18 14:47 UTC, zkochan commented on config/package-is-installable/test/checkPlatform.ts
add some tests that also check not by `current`

2023-10-18 15:07 UTC, zkochan commented
We should also ensure that if someone modifies the `supportedArchitectures` field, pnpm will install the new included artifacts and symlink them to the dependent packages.

2023-10-18 15:45 UTC, nachoaldamav commented
> We should also ensure that if someone modifies the `supportedArchitectures` field, pnpm will install the new included artifacts and symlink them to the dependent packages.

I just tested something, install everything, change the field and install again (keep `pnpm-lock.yaml` and `node_modules`), the new ones will be added but not symlinked, it won't remove anything that was removed from the `package.json`.

2023-10-24 12:47 UTC, zkochan approved these changes

2023-10-24 12:50 UTC, merged

2023-11-12 11:33 UTC, Doni108doni108 commented
Leave a comment

2023-12-03 23:23 UTC, segevfiner commented
@nachoaldamav Why is this in the `package.json` though? Doesn't this make more sense as configuration that can also be set via CLI and config files?