refactor: extract some logics from `core/install`
pnpm/pnpm pull request #8597
Opened 2024-10-02 02:21 UTC by KSXGitHub

2024-10-02 08:59 UTC, zkochan requested changes

2024-10-02 08:59 UTC, zkochan commented on packages/core-utils/src/createObjectChecksum.ts
This function was changed in v10 (https://github.com/pnpm/pnpm/pull/8499), so to avoid conflicts I would do the change on a branch based on v10

2024-10-02 08:59 UTC, zkochan commented on packages/core-utils/src/getOutdatedLockfileSetting.ts
this function is related to lockfiles. I would place it in the lockfile setting and name the package something like `@pnpm/lockfile.settings-checker` or similar.

2024-10-02 10:06 UTC, KSXGitHub commented on packages/core-utils/src/createObjectChecksum.ts
I can't see any way to avoid git conflict unless I the new feature is to be exclusive to v10. I guess I will rename the package to `crypto.object-hasher`. I'll keep the name `createObjectChecksum` since it currently returns a different result from `hashObject`. Later, you can resolve the conflict by changing `createObjectChecksum` to be based on `hashObject`. What do you think?

2024-10-02 10:10 UTC, zkochan commented on packages/core-utils/src/createObjectChecksum.ts
make it exclusive for v10

if really needed, can be later backported to v9

2024-10-04 01:14 UTC, zkochan commented on lockfile/settings-checker/README.md
> +> Utilities to check if lockfile settings is out-of-date.
```suggestion
> Utilities to check if lockfile settings are out-of-date.
```

2024-10-04 01:14 UTC, zkochan commented on lockfile/settings-checker/package.json
> +  "version": "1.0.0",
you start with 0.0.0 then changesets bump it to 1.0.0

2024-10-04 01:55 UTC, KSXGitHub commented on lockfile/settings-checker/README.md
> +> Utilities to check if lockfile settings is out-of-date.
https://github.com/pnpm/pnpm/pull/8597/commits/4782f1c8ce699bdca7701cd7dfd593c2215845aa

2024-10-04 01:56 UTC, KSXGitHub commented on lockfile/settings-checker/package.json
> +  "version": "1.0.0",
https://github.com/pnpm/pnpm/pull/8597/commits/9c9d346fce6a53292397c538eff086b3f43d1928

2024-10-04 02:09 UTC, zkochan approved these changes

2024-10-04 02:27 UTC, merged