fix: disregard `wantedPackageManager` for certain commands
pnpm/pnpm pull request #8685
Opened 2024-10-22 04:19 UTC by xty

Currently, there is a class of CLI commands that at a conceptual level, ought to run "globally" irrespective of the current project. For instance, when running `pnpm self-update`, we really shouldn't care about the `"packageManager"` field (or any other field, in fact) in the project manifest, as the action we're performing isn't concerned with any specific project.

This PR makes sure that for these commands, the `switchCliVersion` and `checkPackageManager` functions will not be called, so that they can be executed smoothly.

close #7959

2024-10-22 20:30 UTC, zkochan commented
I agree that these commands should ignore the `checkPackageManager` check.

But I don't think they should skip `switchCliVersion`, except maybe the `self-update` command.

2024-10-23 17:45 UTC, xty commented
> I agree that these commands should ignore the `checkPackageManager` check.
> 
> But I don't think they should skip `switchCliVersion`, except maybe the `self-update` command.

Sure, I'm on it.

2024-10-23 19:00 UTC, xty commented
As things stand now, `switchCliVersion` and `checkPackageManager` are mutually exclusive, which means at most **only one** of them will be invoked.

https://github.com/pnpm/pnpm/blob/66bcc7a8b55d821bb72cff3fa24e821a2189f978/pnpm/src/main.ts#L110-L114

As a result, so long as `manage-package-manager-versions=true`, pnpm won't complain whatsoever even if `package-manager-strict=true` but we have `"packageManager": "yarn@4.5.1"` in the project's `package.json`.

I'm not sure if this is the intended behaviour. Would you want me to leave it as is or tackle it along the way? @zkochan

2024-10-24 17:48 UTC, zkochan commented
That doesn't seem right. They should not be mutually exclusive when the package manager is not pnpm

2024-11-25 00:37 UTC, zkochan requested changes
I think we should approach this differently. Instead of listing the commands that should ignore the package manager check, we could add some boolean fields to these commands that tell if the specific command should regard or ignore the packageManager field.

2024-11-25 00:58 UTC, zkochan commented
This should work: https://github.com/pnpm/pnpm/pull/8802

2024-11-25 09:13 UTC, closed without merging