fix: `ERR_PNPM_TARBALL_EXTRACT` when the URL's hash contains a slash
pnpm/pnpm pull request #8761
Opened 2024-11-15 07:29 UTC by IceOfSummer

Before determine the URL type, encode the hash if it contains a slash. 

Fix: #7697

2024-11-15 08:00 UTC, IceOfSummer commented
Hello! There is an Eslint error in upstream/main:
```log
pnpm/workspace/state/src/createWorkspaceState.ts
  13:20  error  Require 'compare' argument  @typescript-eslint/require-array-sort-compare
```

I will rebase my branch after this error is resolved. Or should I resolve it myself in this PR?

2024-11-17 13:55 UTC, zkochan requested changes

2024-11-17 13:55 UTC, zkochan commented on resolving/tarball-resolver/src/index.ts
> +  if (!(wantedDependency.pref.startsWith('http:') || wantedDependency.pref.startsWith('https:'))) {
why was this changed? it is unrelated to the fix

2024-11-17 13:55 UTC, zkochan commented on pnpm/test/install/misc.ts
> +    'https://github.com/actions/toolkit.git#core/1.10',
```suggestion
    'https://github.com/pnpm-e2e/simple-pkg.git#branch/with-slash',
```

2024-11-18 00:58 UTC, IceOfSummer commented on resolving/tarball-resolver/src/index.ts
> +  if (!(wantedDependency.pref.startsWith('http:') || wantedDependency.pref.startsWith('https:'))) {
Sorry, this is my own hobby. I think this writing is better for my understanding.

2024-11-18 01:59 UTC, zkochan approved these changes

2024-11-18 02:02 UTC, merged